import { load, save } from './store.js';
import { createId, nowIso, Mastery, recommendedConcepts } from './domain.js';
import { aiService, ocrService } from './services.js';
let data = load(), page = data.user ? 'home' : 'welcome', draftPages = [], selectedCourse = null, extractedText = '';
const app = document.querySelector('#app');
const esc = s => String(s ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const persist = () => save(data);
function toast(message, error = false) { const el = document.createElement('div'); el.className = `toast ${error?'error':''}`; el.textContent = message; document.body.append(el); setTimeout(()=>el.remove(), 4500); }
function shell(title, content, action='') { return `<header><button class="brand" data-go="home">Étudia<span>✦</span></button>${action}</header><section class="view"><div class="eyebrow">${title}</div>${content}</section>${data.user?`<nav><button data-go="home">⌂<small>Accueil</small></button><button data-go="courses">▤<small>Cours</small></button><button data-go="revision">🧠<small>Réviser</small></button><button data-go="progress">◔<small>Progrès</small></button></nav>`:''}`; }
function home() { const courses = data.courses.slice(-3).reverse(); const needed = recommendedConcepts(data.progress); const progress = data.progress.length ? Math.round(data.progress.filter(p=>p.masteryLevel===Mastery.mastered).length/data.progress.length*100) : 0; return shell(`Bonjour ${esc(data.user.name)} 👋`, `<h1>On apprend pas à pas.</h1><div class="hero"><p>Ta prochaine petite séance</p><h2>${needed.length ? `Réviser ${esc(needed[0].conceptName)}` : 'Crée ton premier cours'}</h2><p>${needed.length ? '15 minutes • selon tes dernières réponses' : 'Commence par un titre ou tes notes.'}</p><button class="primary" data-go="revision">Commencer</button></div><div class="metric"><b>${progress}%</b><span>Progression globale</span><div><i style="width:${progress}%"></i></div></div><h2>Commencer</h2><div class="actions"><button data-go="scan">📸<b>Scanner un cours</b><small>Photos et texte à vérifier</small></button><button data-go="create">✨<b>Créer un cours</b><small>À partir d'un titre</small></button><button data-go="revision">🧠<b>Réviser</b><small>Une session adaptée</small></button><button data-go="progress">📊<b>Ma progression</b><small>Voir tes acquis</small></button></div><h2>Cours récents</h2>${courses.length?`<div class="list">${courses.map(courseCard).join('')}</div>`:'<p class="empty">Aucun cours pour l’instant. Choisis une façon de commencer ci-dessus.</p>'}<h2>À revoir</h2>${needed.length?needed.map(p=>`<div class="row"><b>${esc(p.conceptName)}</b><span class="tag fragile">${p.masteryLevel}</span></div>`).join(''):'<p class="empty">Tes difficultés apparaîtront ici après tes premières activités.</p>'}`); }
function courseCard(c) { return `<button class="course-card" data-course="${c.id}"><span>${c.sourceType==='scanned'?'📸':'✨'}</span><div><b>${esc(c.title)}</b><small>${esc(c.subject || 'Sans matière')} · ${new Date(c.updatedAt).toLocaleDateString('fr-FR')}</small></div><em>›</em></button>`; }
function create() { return shell('Nouveau cours', `<h1>De quoi veux-tu apprendre ?</h1><p class="lead">Donne seulement le titre. Les détails sont optionnels.</p><form id="create-form" class="form"><label>Titre de la leçon<input required name="title" placeholder="Ex. Les fonctions affines"></label><label>Matière (optionnel)<input name="subject" placeholder="Ex. Mathématiques"></label><label>Niveau scolaire (optionnel)<input name="level" placeholder="Ex. 4e"></label><label>Explication<select name="difficulty"><option>Très simple</option><option selected>Normal</option><option>Approfondissement</option></select></label><button class="primary" type="submit">Créer mon cours</button></form><p class="notice">La génération est réalisée par le serveur Étudia configuré, jamais avec une clé secrète dans l’app.</p>`); }
function scan() { return shell('Scanner un cours', `<h1>Ajoute les pages de ton cahier</h1><p class="lead">Tu pourras réorganiser les pages, puis vérifier le texte avant de générer le cours.</p><label class="upload">📷<b>Choisir des photos</b><small>JPG, PNG ou HEIC</small><input id="pages" type="file" accept="image/*" multiple></label><div id="page-list" class="pages">${renderPages()}</div><button id="extract" class="primary" ${draftPages.length?'':'disabled'}>Lire le texte des ${draftPages.length} page(s)</button><p class="notice">L’OCR peut se tromper, surtout sur l’écriture manuscrite. Vérifie toujours le texte.</p>`); }
function renderPages(){return draftPages.map((p,i)=>`<div class="page"><img src="${p.preview}" alt="Page ${i+1}"><span>Page ${i+1}</span><button data-page="up:${i}" ${i?'':'disabled'}>↑</button><button data-page="down:${i}" ${i<draftPages.length-1?'':'disabled'}>↓</button><button data-page="delete:${i}">Supprimer</button></div>`).join('');}
function scanReview(){ return shell('Vérifier le texte',`<h1>Relis avant de générer</h1><p class="lead">Ce texte vient de l’OCR et peut contenir des erreurs. Les futures explications IA seront clairement séparées.</p><form id="scan-review" class="form"><label>Texte extrait<textarea required name="text" rows="12">${esc(extractedText)}</textarea></label><label>Titre du cours<input required name="title" placeholder="Ex. La proportionnalité"></label><label>Matière<input name="subject" placeholder="Ex. Mathématiques"></label><button class="primary">Créer la fiche à partir de ce texte</button></form>`); }
function courses() { return shell('Mes cours', `<h1>Retrouve tes leçons</h1><input id="search" class="search" placeholder="Rechercher un cours, une matière…"><div id="courses-list" class="list">${data.courses.length ? data.courses.slice().reverse().map(courseCard).join('') : '<p class="empty">Aucun cours enregistré.</p>'}</div>`, '<button class="header-add" data-go="create">＋</button>'); }
function courseDetail(c) { const generated=c.generatedContent||{}; return shell(esc(c.subject||'Cours'), `<button class="back" data-go="courses">← Tous les cours</button><h1>${esc(c.title)}</h1><p class="source">${c.sourceType==='scanned'?'Contenu extrait de tes pages — à distinguer des explications IA.':'Cours généré à ta demande.'}</p>${c.originalContent?`<details><summary>Texte original fourni</summary><p>${esc(c.originalContent)}</p></details>`:''}<div class="sections">${(generated.sections||[]).map(s=>`<article><h2>${esc(s.title)}</h2><p>${esc(s.content)}</p></article>`).join('')}</div><div class="toolbar"><button data-ask="${c.id}">🤖 Demander à l’IA</button><button data-delete="${c.id}">Supprimer</button></div>`); }
function revision(){ const concepts=recommendedConcepts(data.progress); return shell('Ma prochaine révision', `<h1>Une séance courte et utile</h1>${concepts.length?`<div class="hero"><p>Session de 15 minutes</p><h2>${concepts.length} notion(s) à consolider</h2><p>3 flashcards · 3 questions · 1 exercice</p><button id="start-revision" class="primary">Commencer la session</button></div><div class="list">${concepts.map(p=>`<div class="row"><b>${esc(p.conceptName)}</b><span class="tag fragile">${esc(p.masteryLevel)}</span></div>`).join('')}</div>`:'<p class="empty">Réponds à des quiz ou ajoute un cours pour obtenir des révisions personnalisées.</p>'}`); }
function progress(){ const concepts=data.progress; const mastered=concepts.filter(p=>p.masteryLevel===Mastery.mastered); const fragile=concepts.filter(p=>p.masteryLevel===Mastery.fragile); return shell('Ma progression', `<h1>Ce qui compte pour toi</h1><div class="stats"><div><b>${data.courses.length}</b><span>Cours</span></div><div><b>${mastered.length}</b><span>Maîtrisées</span></div><div><b>${fragile.length}</b><span>À revoir</span></div></div><h2>Ce que je maîtrise</h2>${mastered.length?mastered.map(p=>`<div class="row"><b>${esc(p.conceptName)}</b><span class="tag">${p.masteryLevel}</span></div>`).join(''):'<p class="empty">Une notion devient maîtrisée grâce à plusieurs réussites.</p>'}<h2>À travailler maintenant</h2>${fragile.length?fragile.map(p=>`<div class="row"><b>${esc(p.conceptName)}</b><span class="tag fragile">${p.masteryLevel}</span></div>`).join(''):'<p class="empty">Aucune difficulté détectée pour le moment.</p>'}`); }
function welcome(){ return `<section class="welcome"><div class="logo">Étudia <span>✦</span></div><p class="eyebrow">Ton tuteur personnel</p><h1>Comprendre, apprendre et réviser à ton rythme.</h1><ol><li>📸 Scanne les pages de ton cahier.</li><li>✨ Crée une leçon avec son titre.</li><li>🤖 Demande une explication autrement.</li><li>🧠 Entraîne-toi avec quiz et exercices.</li><li>📅 Organise des révisions adaptées.</li></ol><button class="primary" data-go="profile">Commencer</button></section>`; }
function profile(){return `<section class="welcome"><div class="logo">Étudia <span>✦</span></div><h1>Faisons connaissance</h1><form id="profile-form" class="form"><label>Ton prénom<input required name="name" maxlength="50" autocomplete="given-name"></label><label>Ton niveau scolaire<input required name="level" placeholder="Ex. 4e"></label><button class="primary">Entrer dans Étudia</button></form></section>`;}
function render(){ selectedCourse && (page='course'); const views={welcome,profile,home,create,scan,scanReview,courses,revision,progress,course:()=>courseDetail(selectedCourse)}; app.innerHTML=views[page](); bind(); }
function bind(){ document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{page=b.dataset.go;selectedCourse=null;render();}); document.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>{selectedCourse=data.courses.find(c=>c.id===b.dataset.course);render();}); const pf=document.querySelector('#profile-form'); if(pf)pf.onsubmit=e=>{e.preventDefault();const f=new FormData(pf);data.user={id:createId('user'),name:f.get('name').trim(),schoolLevel:f.get('level').trim(),createdAt:nowIso()};persist();page='home';render();}; const cf=document.querySelector('#create-form');if(cf)cf.onsubmit=generateFromForm; const sf=document.querySelector('#scan-review');if(sf)sf.onsubmit=analyzeScan; const input=document.querySelector('#pages');if(input)input.onchange=addPages; document.querySelectorAll('[data-page]').forEach(b=>b.onclick=managePage); const ex=document.querySelector('#extract');if(ex)ex.onclick=extractPages; const search=document.querySelector('#search');if(search)search.oninput=()=>{const q=search.value.toLowerCase();document.querySelector('#courses-list').innerHTML=data.courses.filter(c=>`${c.title} ${c.subject}`.toLowerCase().includes(q)).slice().reverse().map(courseCard).join('')||'<p class="empty">Aucun résultat.</p>';document.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>{selectedCourse=data.courses.find(c=>c.id===b.dataset.course);render();});}; document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{data.courses=data.courses.filter(c=>c.id!==b.dataset.delete);persist();page='courses';selectedCourse=null;render();}); document.querySelectorAll('[data-ask]').forEach(b=>b.onclick=askAI); const start=document.querySelector('#start-revision');if(start)start.onclick=()=>toast('Les activités de révision seront disponibles lorsque le serveur générera les quiz, exercices et flashcards.'); }
async function generateFromForm(e){e.preventDefault();const f=new FormData(e.currentTarget),button=e.currentTarget.querySelector('button');button.disabled=true;button.textContent='Création en cours…';try{const generated=await aiService.generateCourse({title:f.get('title').trim(),subject:f.get('subject').trim(),schoolLevel:f.get('level').trim()||data.user.schoolLevel,difficulty:f.get('difficulty'),language:'fr',objective:'Comprendre puis s’entraîner progressivement.'});saveCourse(generated,{title:f.get('title').trim(),subject:f.get('subject').trim(),sourceType:'generated'});toast('Cours créé et enregistré.');page='courses';render();}catch(err){toast(err.message,true);button.disabled=false;button.textContent='Créer mon cours';}}
function addPages(e){for(const file of e.target.files){if(!file.type.startsWith('image/'))continue;draftPages.push({name:file.name,preview:URL.createObjectURL(file),file});}render();}
function managePage(e){const [action,indexText]=e.currentTarget.dataset.page.split(':');const index=Number(indexText);if(action==='delete'){URL.revokeObjectURL(draftPages[index].preview);draftPages.splice(index,1);}else{const target=action==='up'?index-1:index+1;[draftPages[index],draftPages[target]]=[draftPages[target],draftPages[index]];}render();}
async function extractPages(){const button=document.querySelector('#extract');button.disabled=true;button.textContent='Lecture du texte…';try{const pages=await Promise.all(draftPages.map(async p=>({name:p.name,data:await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(p.file);})})));extractedText=await ocrService.extract(pages);page='scanReview';render();}catch(err){toast(err.message,true);button.disabled=false;button.textContent=`Lire le texte des ${draftPages.length} page(s)`;}}
async function analyzeScan(e){e.preventDefault();const f=new FormData(e.currentTarget),btn=e.currentTarget.querySelector('button');btn.disabled=true;btn.textContent='Analyse du cours…';try{const originalContent=f.get('text').trim();const generated=await aiService.analyzeCourse({title:f.get('title').trim(),subject:f.get('subject').trim(),schoolLevel:data.user.schoolLevel,originalContent,language:'fr'});saveCourse(generated,{title:f.get('title').trim(),subject:f.get('subject').trim(),sourceType:'scanned',originalContent});draftPages.forEach(p=>URL.revokeObjectURL(p.preview));draftPages=[];page='courses';render();toast('Fiche créée et enregistrée.');}catch(err){toast(err.message,true);btn.disabled=false;btn.textContent='Créer la fiche à partir de ce texte';}}
function saveCourse(generated,meta){const course={id:createId('course'),userId:data.user.id,title:generated.title||meta.title,subject:meta.subject,sourceType:meta.sourceType,originalContent:meta.originalContent||null,generatedContent:generated,createdAt:nowIso(),updatedAt:nowIso()};data.courses.push(course);for(const concept of generated.concepts||[]){data.progress.push({id:createId('progress'),courseId:course.id,conceptName:typeof concept==='string'?concept:concept.name,masteryLevel:Mastery.new,correctAnswers:0,incorrectAnswers:0,nextReviewAt:nowIso()});}persist();}
async function askAI(e){const course=data.courses.find(c=>c.id===e.currentTarget.dataset.ask);const question=prompt('Quelle partie souhaites-tu comprendre ?');if(!question?.trim())return;try{const answer=await aiService.answerQuestion({courseTitle:course.title,courseContent:course.generatedContent,question:question.trim(),pedagogy:'Guide l’élève avec un indice, la méthode, puis une explication. Ne donne pas immédiatement une réponse d’exercice.'});alert(answer);}catch(err){toast(err.message,true);}}
render();
